### ISSUE TITLE
WSUS on Windows Server 2019

### ISSUE THREAD

**Issue by jannikk09** [r4yfx/wsus-grafana#4]
Hi, is the script compatible with Windows Server 2019?
I installed everything but no data in Grafana or InfluxDB.

I installed Docker on Windows VM with WSL2 and all requierments. 
Grafana is installed local and not with a container.

**Comment by r4yfx** [comment]
@jannikk09 this script was written before 2019 and there wasnt compatible. There is a new pull within the script which looks at newer versions of windows and should work
