### ISSUE TITLE
Data are not rounded

### ISSUE THREAD

**Issue by judzk** [r4yfx/wsus-grafana#6]
Hi, i put wsus on a windows server 2019 std and the stats are not rounded :
My powershell result :
> wsusstats,host=wsus windows10=302 1656667449000000000
> wsusstats,host=wsus windows11=0 1656667449000000000
> wsusstats,host=wsus windows2019st=11 1656667449000000000
> wsusstats,host=wsus windows2016=0 1656667449000000000
> wsusstats,host=wsus criticalupdates=0 1656667449000000000
> wsusstats,host=wsus updates=0 1656667449000000000
> wsusstats,host=wsus sp=0 1656667449000000000
> wsusstats,host=wsus numberofclients=315 1656667449000000000
> wsusstats,host=wsus requpdates=95 1656667449000000000
> wsusstats,host=wsus failed=5 1656667449000000000
> wsusstats,host=wsus reqreboot=29 1656667449000000000

My grafana dashboard:
<img width="416" alt="image" src="https://user-images.githubusercontent.com/26792639/176867707-6ed2e6b1-6198-420d-b827-5ad52e50dabf.png">
My dashboard code :
SELECT mean("windows2019st") FROM "wsusstats" WHERE ("host" = 'wsus') AND $timeFilter GROUP BY time($__interval) fill(null)
SELECT mean("windows10") FROM "wsusstats" WHERE ("host" = 'wsus') AND $timeFilter GROUP BY time($__interval) fill(null)
Any idea?

**Comment by r4yfx** [comment]
@judzk this script was written before 2019 and there wasnt compatible. There is a new pull within the script which looks at newer versions of windows and should work
